version: 0.2

env:
  shell: 
phases:
  pre_build:
    commands:
      - sh "cat index.html"
  build:
    commands:
      - sh "echo continuando"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
